---
- name: Gather only network facts
  ansible.builtin.setup:
    gather_subset:
      - network

- name: Fetch all important ip addresses
  ansible.builtin.set_fact:
    container_name: "watchtower"
    network_name: "lsio"
    public_ipv4: >-
      {{ ansible_facts['default_ipv4']['address'] }}
    public_ipv6: >-
      {{ ansible_facts['default_ipv6']['address'] | default('::1') }}
    tailscale_ipv4: >-
      {{ ansible_facts['tailscale0']['ipv4']['address'] }}
    tailscale_ipv6: >-
      {{ ansible_facts['tailscale0']['ipv6'] | selectattr('scope', 'equalto', 'global') | map(attribute='address') | list | first }}
    puid: >-
      {{ ansible_facts['effective_user_id'] }}
    pgid: >-
      {{ ansible_facts['effective_group_id'] }}

- name: Show all important IP addresses
  ansible.builtin.debug:
    msg: |
      Default IPv4: {{ public_ipv4 }}
      Default IPv6: {{ public_ipv6 }}
      Tailscale IPv4: {{ tailscale_ipv4 }}
      Tailscale IPv6: {{ tailscale_ipv6 }}

- name: Ensure directories for {{ container_name }} exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ ansible_env.HOME }}/docker/composes/{{ container_name }}-docker/"


- name: Render {{ container_name }} docker-compose.yml on remote
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ ansible_env.HOME }}/docker/composes/{{ container_name }}-docker/docker-compose.yml"
    mode: "0644"

- name: Ensure directories for {{ container_name }} exist locally
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "../../../docker_composes/{{ inventory_hostname }}/{{ container_name }}-docker/"
  delegate_to: localhost

- name: Render traefik docker-compose.yml on local
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "../../../docker_composes/{{ inventory_hostname }}/{{ container_name }}-docker/docker-compose.yml"
    mode: "0644"
  delegate_to: localhost

- name: Render traefik .env
  ansible.builtin.template:
    src: templates/.env.j2
    dest: "../../../docker_composes/{{ inventory_hostname }}/{{ container_name }}-docker/.env"
    mode: "0644"
  delegate_to: localhost
