- name: Install Python docker package via geerlingguy.pip
  include_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: docker

- name: Install Docker engine via geerlingguy.docker
  include_role:
    name: geerlingguy.docker

- name: Create Docker networks
  community.docker.docker_network:
    name: "{{ item }}"
    driver: bridge
    state: present
  loop: "{{ common_docker_networks }}"

- name: Set Tailscale Auth Key
  set_fact:
    tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"

- name: Install Tailscale
  include_role:
    name: artis3n.tailscale
