version: '3'

services:
  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`overwatch.andywebservices.com`)
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.tls.certresolver=zerossl
    networks:
      - lsio
    restart: unless-stopped

networks:
  lsio:
    external: true