version: '3'

services:
  whoami:
    container_name: whoami
    # A container that exposes an API to show its IP address
    image: traefik/whoami:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`${WHOAMI_URL}`)
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.tls.certresolver=zerossl
    networks:
      - lsio
    restart: unless-stopped

networks:
  lsio:
    external: true
