name: Pulumi tailscale nextdns rewrite on PR

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'tailscale/nextdns/*.yaml'
      - '.github/workflows/pulumi-ts-nd-rewrites.yml'

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'tailscale/nextdns/'
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Installing dependencies
        run: pip install -r requirements.txt

      - name: Load 1Password secrets
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          PULUMI_ACCESS_TOKEN: op://aws-svcs/t64a4xf274evgaef62gohwzeqa/credential
          NEXTDNS_API_TOKEN: op://aws-svcs/ktcu4b6pzncz464rd5owerxsku/token
          TAILSCALE_API_KEY: op://aws-svcs/7f67qgmdvqjl6qghuccxswbham/key

      - uses: pulumi/actions@v6
        id: preview
        with:
          work-dir: 'tailscale/nextdns/'
          command: preview
          stack-name: AndyWebServices/infra-tailscale-nextdns-rewrites/prod
          comment-on-pr: true
