name: Deploy OpenTofu Tailscale AWS Tailnet On PR

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'tailscale/aws_tailnet/*.tf'
      - 'tailscale/aws_tailnet/*.tfvars'
      - '.github/workflows/tofu-tailscale-aws-tailnet.yml'
      - '.github/actions/reusable-tofu/action.yml'

jobs:
  setup-env:
    name: Setup Environment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'cloudflare/zone_aws'
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Load secrets
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          # B2 backend keys
          TF_VAR_b2_access_key_id: op://aws-svcs/hctngt5ggvrvmx4nt56v3c7b6q/keyID
          TF_VAR_b2_secret_access_key: op://aws-svcs/hctngt5ggvrvmx4nt56v3c7b6q/applicationKey
          # Tailscale OAuth keys
          TF_VAR_tailscale_client_id: op://aws-svcs/7f67qgmdvqjl6qghuccxswbham/key
          TF_VAR_tailscale_client_secret: op://aws-svcs/7f67qgmdvqjl6qghuccxswbham/tailnet
          # Tailscale admin/member user names
          TF_VAR_member_user: op://aws-svcs/7f67qgmdvqjl6qghuccxswbham/admin_user
          TF_VAR_admin_user: op://aws-svcs/7f67qgmdvqjl6qghuccxswbham/member_user

      - name: Run re-usable tofu
        uses: ./.github/actions/reusable-tofu
        with:
          uniq-name: "OpenTofu Tailscale Tailnet AWS"
          working-directory: "tailscale/aws_tailnet/"
          github-token: ${{ secrets.GITHUB_TOKEN }}
