name: Deploy OpenTofu Cloud

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'cloud/*.tf'
      - '.github/workflows/tofu-cloud.yml'
      - '.github/actions/reusable-tofu/action.yml'

jobs:
  setup-env:
    name: Setup Environment
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Load secrets
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          # B2 backend keys
          TF_VAR_b2_access_key_id: op://aws-svcs/hctngt5ggvrvmx4nt56v3c7b6q/keyID
          TF_VAR_b2_secret_access_key: op://aws-svcs/hctngt5ggvrvmx4nt56v3c7b6q/applicationKey
          # Cloudflare Token
          TF_VAR_cf_api_token: op://aws-svcs/ozxn4ucjnnymr3bnbs6oonpmke/token
          # IP addresses
          TF_VAR_cf_aws_chicago_ipv4: op://aws-svcs/ub5j7tuvg22mzrndyyqxfn3bpi/aws_chicago_ipv4
          TF_VAR_authentik_ipv4: op://aws-svcs/ub5j7tuvg22mzrndyyqxfn3bpi/authentik_ipv4
          TF_VAR_overwatch_ipv4: op://aws-svcs/ub5j7tuvg22mzrndyyqxfn3bpi/overwatch_ipv4
          # Oracle Cloud Infra
          TF_VAR_oci_tenancy_ocid: op://aws-svcs/gl2ruywhokyxow6x42nb67mdx4/oci_tenancy_ocid
          TF_VAR_oci_user_ocid: op://aws-svcs/gl2ruywhokyxow6x42nb67mdx4/oci_user_ocid
          TF_VAR_oci_fingerprint: op://aws-svcs/kcv64xrfh46qe4ygputgoqzlx4/oci_fingerprint
          TF_VAR_oci_private_key: "op://aws-svcs/kcv64xrfh46qe4ygputgoqzlx4/private key"
          TF_VAR_oci_region: op://aws-svcs/gl2ruywhokyxow6x42nb67mdx4/oci_region
          TF_VAR_oci_ssh_authorized_keys: "op://aws-svcs/xf2kkmka32qlvu6jleafrbnyre/public key"

      - name: Run re-usable tofu
        uses: ./.github/actions/reusable-tofu
        with:
          uniq-name: "OpenTofu Cloudflare Zone AWS"
          working-directory: "cloud/"
          github-token: ${{ secrets.GITHUB_TOKEN }}
