name: Deploy OpenTofu Tailscale AWS Tailnet On PR

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'k3s/k1/*.tf'
      - 'k3s/k1/*.tfvars'
      - '.github/workflows/tofu-k3s-k1.yml'
      - '.github/actions/reusable-tofu/action.yml'

jobs:
  setup-env:
    name: Setup Environment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'k3s/k1'
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Load secrets
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          AWS_ACCESS_KEY_ID: op://aws-svcs/hctngt5ggvrvmx4nt56v3c7b6q/keyID
          AWS_SECRET_ACCESS_KEY: op://aws-svcs/hctngt5ggvrvmx4nt56v3c7b6q/applicationKey

          TF_VAR_tailscale_client_id: "op://aws-svcs/grw65fzqcu3ip7bvu53c7issw4/Client ID"
          TF_VAR_tailscale_client_secret: "op://aws-svcs/grw65fzqcu3ip7bvu53c7issw4/Client Secret"
          TF_VAR_cloudflare_api_token: op://aws-svcs/ozxn4ucjnnymr3bnbs6oonpmke/token
          TF_VAR_longhorn_backup_cifs_username: op://aws-svcs/vwinxzfaddhrv7boqxmt5ydz2y/username
          TF_VAR_longhorn_backup_cifs_password: op://aws-svcs/vwinxzfaddhrv7boqxmt5ydz2y/password

      - name: Run re-usable tofu
        uses: ./.github/actions/reusable-tofu
        with:
          uniq-name: "OpenTofu Tailscale Tailnet AWS"
          working-directory: 'k3s/k1'
          github-token: ${{ secrets.GITHUB_TOKEN }}
